app1/urls.py
from django.urls import path
from app1.views import *
app_name = 'jithu'

urlpatterns = [
    path("ikka/", ikka, name='ikka'),
]

project8/urls.py
from django.contrib import admin
from django.urls import path, include
from app2.views import *
import app1

urlpatterns = [
    path("admin/", admin.site.urls),
    path("lal/", lal, name='lal'),
    path("app1/", include('app1.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.


def ikka(request):
    return render(request, 'ikka.html')

app2/views.py
from django.shortcuts import render

# Create your views here.


def lal(request):
    return render(request, 'lal.html')

templates/ikka.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <center>
      <h1>Lalu I Love u so much</h1>
      <a href="{% url 'lal' %}">go to lalu</a>
    </center>
  </body>
</html>

templates/lal.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <center>
      <h1>Ikkachi I LOVE U TOOOOOOO.....</h1>
      <a href="{% url 'jithu:ikka' %}">go to ikka</a>
    </center>
  </body>
</html>